version: '3.8'

services:

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: devops
      MYSQL_USER: root
      MYSQL_PASSWORD: rootcode
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spring:
    build: ./spring-app
    restart: on-failure
    depends_on:
      - mysql
    ports:
      - "8082:8082"

  angular:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - spring

volumes:
  mysql_data:


